# --- !Ups

create table "user" ("userID" VARCHAR NOT NULL PRIMARY KEY,"firstName" VARCHAR,"lastName" VARCHAR,"fullName" VARCHAR, "email" VARCHAR,"avatarURL" VARCHAR, "score" INT NOT NULL);

create table "friends" ("userID" VARCHAR NOT NULL, "friendID" VARCHAR NOT NULL, FOREIGN KEY ("userID") REFERENCES "user"("userID"), FOREIGN KEY ("friendID") REFERENCES "user"("userID"));

create table "logininfo" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, "providerID" VARCHAR NOT NULL,"providerKey" VARCHAR NOT NULL);

create table "userlogininfo" ("userID" VARCHAR NOT NULL,"loginInfoId" BIGINT NOT NULL, FOREIGN KEY ("userID") REFERENCES "user"("userID"), FOREIGN KEY ("loginInfoId") REFERENCES "logininfo"("id"));

create table "oauth2info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, "accesstoken" VARCHAR NOT NULL,"tokentype" VARCHAR,"expiresin" INTEGER,"refreshtoken" VARCHAR,"logininfoid" BIGINT NOT NULL, FOREIGN KEY ("logininfoid") REFERENCES "logininfo"("id"));



# --- !Downs

drop table "oauth2info";
drop table "userlogininfo";
drop table "logininfo";
drop table "user";